/* Generated by Nim Compiler v0.17.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/opt/apps/nim/nim-0.17.0/lib -o /mnt/pcie/workspaces/workspace-nim/get_ext_list/src/nimcache/get_ext_list_get_ext_list.o /mnt/pcie/workspaces/workspace-nim/get_ext_list/src/nimcache/get_ext_list_get_ext_list.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <dirent.h>
#include <setjmp.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <time.h>
#include <stdio.h>
#include <stdlib.h>
#undef linux
#undef near
typedef struct Table_8Uf9bmzgz4A6eZu5h8HqdYA Table_8Uf9bmzgz4A6eZu5h8HqdYA;
typedef struct TY_9bzblIv39b19bLtyTzpVFK81g TY_9bzblIv39b19bLtyTzpVFK81g;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TY_Tl2uHUsuLSQf9bN9bZowWv4Q TY_Tl2uHUsuLSQf9bN9bZowWv4Q;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY_mGuTghb7gdfMB1AQA9bfeJw TY_mGuTghb7gdfMB1AQA9bfeJw;
typedef struct TY_sM4lkSb7zS6F7OVMvW9cffQ TY_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct Cell_1zcF9cV8XIAtbN8h5HRUB8g Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct CellSeq_Axo1XVm9aaQueTOldv8le5w CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct GcHeap_1TRH1TZMaVZTnLNcIHuNFQ GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct GcStack_7fytPA5bBsob6See21YMRA GcStack_7fytPA5bBsob6See21YMRA;
typedef struct MemRegion_x81NhDv59b8ercDZ9bi85jyg MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct SmallChunk_tXn60W2f8h3jgAYdEmy5NQ SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct LLChunk_XsENErzHIZV9bhvyJx56wGw LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct BigChunk_Rv9c70Uhp2TytkX7eH78qEg BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct IntSet_EZObFrE3NC9bIb3YMkY9crZA IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct AvlNode_IaqjtwKhxLEpvDS9bct9blEw AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct TY_ujsjpB2O9cjj3uDHsXbnSzg TY_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct GcStat_0RwLoVBHZPfUAcLczmfQAg GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct CellSet_jG87P0AI9aZtss9ccTYBIISQ CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct PageDesc_fublkgIY4LG3mT51LU2WHg PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TSafePoint TSafePoint;
typedef struct TY_7q7q3E6Oj24ZNVJb9aonhAg TY_7q7q3E6Oj24ZNVJb9aonhAg;
typedef struct Env_get_ext_listdotnim__M8m6n7N3H9cit7ldWho4FaQ Env_get_ext_listdotnim__M8m6n7N3H9cit7ldWho4FaQ;
typedef struct BaseChunk_Sdq7WpT6qAH858F5ZEdG3w BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct FreeCell_u6M5LHprqzkn9axr04yg9bGQ FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TY_9bzblIv39b19bLtyTzpVFK81g {
NI Field0;
NI64 Field1;
};
typedef NU8 TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct  TNimType  {
NI size;
TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Table_8Uf9bmzgz4A6eZu5h8HqdYA  {
TY_Tl2uHUsuLSQf9bN9bZowWv4Q* data;
NI counter;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct TY_mGuTghb7gdfMB1AQA9bfeJw {
NI Field0;
NimStringDesc* Field1;
TY_9bzblIv39b19bLtyTzpVFK81g Field2;
};
struct  Cell_1zcF9cV8XIAtbN8h5HRUB8g  {
NI refcount;
TNimType* typ;
};
struct  GcStack_7fytPA5bBsob6See21YMRA  {
void* bottom;
};
struct  CellSeq_Axo1XVm9aaQueTOldv8le5w  {
NI len;
NI cap;
Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* TY_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef Trunk_W0r8S0Y3UGke6T9bIUWnnuw* TY_lh2A89ahMmYg9bCmpVaplLbA[256];
struct  IntSet_EZObFrE3NC9bIb3YMkY9crZA  {
TY_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef AvlNode_IaqjtwKhxLEpvDS9bct9blEw* TY_0aOLqZchNi8nWtMTi8ND8w[2];
struct  AvlNode_IaqjtwKhxLEpvDS9bct9blEw  {
TY_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct TY_ujsjpB2O9cjj3uDHsXbnSzg {
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef TY_ujsjpB2O9cjj3uDHsXbnSzg TY_LzOv2eCDGiceMKQstCLmhw[30];
struct  HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg  {
NI len;
TY_LzOv2eCDGiceMKQstCLmhw chunks;
HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct  MemRegion_x81NhDv59b8ercDZ9bi85jyg  {
NI minLargeObj;
NI maxLargeObj;
TY_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct  GcStat_0RwLoVBHZPfUAcLczmfQAg  {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct  CellSet_jG87P0AI9aZtss9ccTYBIISQ  {
NI counter;
NI max;
PageDesc_fublkgIY4LG3mT51LU2WHg* head;
PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct  GcHeap_1TRH1TZMaVZTnLNcIHuNFQ  {
GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
typedef NU8 PathComponent_9c1SIU9cO1wHcl09b703A9cDrg;
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef long TY_TcvIiMAJvcwzNLsZkfnFnQ[25];
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} TY_KeeAOYBd84Ofsw6Y7LizaQ;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
typedef char TY_XKk9bNZbVEtY3RuROG9aRBgw[256];
typedef long TY_QS4edQct6fXoghbs69aZ9a8w[3];
struct TY_7q7q3E6Oj24ZNVJb9aonhAg {
NimStringDesc* Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
typedef struct {
N_NIMCALL_PTR(NI, ClP_0) (NimStringDesc* x, NimStringDesc* y, void* ClE_0);
void* ClE_0;
} TY_kTj9c3SX9agxDQPZYwemi6ug;
typedef NU8 SortOrder_8iBc6wlNqBa9cju9cUAhUAxA;
struct  Env_get_ext_listdotnim__M8m6n7N3H9cit7ldWho4FaQ  {
NI colonstate_;
Table_8Uf9bmzgz4A6eZu5h8HqdYA ret1;
};
typedef struct {
N_NIMCALL_PTR(TY_sM4lkSb7zS6F7OVMvW9cffQ*, ClP_0) (void* ClE_0);
void* ClE_0;
} TY_jGa0TDlm1RK7NwnvKCTNkQ;
typedef N_CLOSURE_PTR(TY_sM4lkSb7zS6F7OVMvW9cffQ*, TM_4VP2PpByWPwo6q1BAjkSNA_21) (void);
typedef N_CLOSURE_PTR(NI, TM_4VP2PpByWPwo6q1BAjkSNA_23) (NimStringDesc* x, NimStringDesc* y, void* ClE_0);
typedef N_NIMCALL_PTR(void, TY_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w  {
NI prevSize;
NI size;
};
struct  SmallChunk_tXn60W2f8h3jgAYdEmy5NQ  {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct  LLChunk_XsENErzHIZV9bhvyJx56wGw  {
NI size;
NI acc;
LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct  BigChunk_Rv9c70Uhp2TytkX7eH78qEg  {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI TY_9a8QARi5WsUggNU9bom7kzTQ[8];
struct  Trunk_W0r8S0Y3UGke6T9bIUWnnuw  {
Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  PageDesc_fublkgIY4LG3mT51LU2WHg  {
PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  FreeCell_u6M5LHprqzkn9axr04yg9bGQ  {
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct TY_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct TY_Tl2uHUsuLSQf9bN9bZowWv4Q {
  TGenericSeq Sup;
  TY_mGuTghb7gdfMB1AQA9bfeJw data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, initTable_dOIBg8E67Yg7t5EIsoQ9aHA)(NI initialSize, Table_8Uf9bmzgz4A6eZu5h8HqdYA* Result);
N_NIMCALL(NIM_BOOL, contains_mfFNyKdgINDteTqTsOLSEg)(Table_8Uf9bmzgz4A6eZu5h8HqdYA t, NimStringDesc* key);
N_NIMCALL(NIM_BOOL, hasKey_mfFNyKdgINDteTqTsOLSEg_2)(Table_8Uf9bmzgz4A6eZu5h8HqdYA t, NimStringDesc* key);
static N_INLINE(NI, rawGet_9bnUTGHGTuHO3gGzrEbHDLgtables)(Table_8Uf9bmzgz4A6eZu5h8HqdYA t, NimStringDesc* key, NI* hc);
N_NIMCALL(NI, hash_uBstFm5SYVQeOL3j9c9bc58A)(NimStringDesc* x);
static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(void, X5BX5Deq__3D7DhGkFWUzQM9auF2Bibyg)(Table_8Uf9bmzgz4A6eZu5h8HqdYA* t, NimStringDesc* key, TY_9bzblIv39b19bLtyTzpVFK81g val);
N_NIMCALL(void, enlarge_rNdZQ4agBlNdtMX39bhshmg)(Table_8Uf9bmzgz4A6eZu5h8HqdYA* t);
N_NIMCALL(void, rawInsert_PEFjCnre9brgFg4bozkOH8w)(Table_8Uf9bmzgz4A6eZu5h8HqdYA* t, TY_Tl2uHUsuLSQf9bN9bZowWv4Q** data, NimStringDesc* key, TY_9bzblIv39b19bLtyTzpVFK81g val, NI hc, NI h);
static N_INLINE(NI, rawGetKnownHC_7x9ckJURtS0mgZKGnBgeeuAtables)(Table_8Uf9bmzgz4A6eZu5h8HqdYA t, NimStringDesc* key, NI hc);
N_NIMCALL(TY_9bzblIv39b19bLtyTzpVFK81g*, X5BX5D__bMIBZN5tX7RVZpP2qmV9cZQ)(Table_8Uf9bmzgz4A6eZu5h8HqdYA* t, NimStringDesc* key);
N_NIMCALL(void, get_ext_list_impl3_nKD3l9cckmFuiRs7pvUgtKQ)(NimStringDesc* startPath, Table_8Uf9bmzgz4A6eZu5h8HqdYA* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(CellSeq_Axo1XVm9aaQueTOldv8le5w* s, Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NimStringDesc*, pop_9cDsfK2acP02vJ9bhxIE9caEAos)(TY_sM4lkSb7zS6F7OVMvW9cffQ** s);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(NimStringDesc*, slash__lXoMhn1ZYc9cAJa9bfA61msg)(NimStringDesc* head, NimStringDesc* tail);
static N_INLINE(NIM_BOOL, dirExists_wf0Ae3eLXw0lSNEFJMV3ogget_ext_list)(NimStringDesc* dir);
N_NIMCALL(NIM_BOOL, nosexistsDir)(NimStringDesc* dir);
N_NIMCALL(NIM_BOOL, nosexistsFile)(NimStringDesc* filename);
N_NIMCALL(void, nossplitFile)(NimStringDesc* path, TY_7q7q3E6Oj24ZNVJb9aonhAg* Result);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NI64, nosgetFileSize)(NimStringDesc* file);
static N_INLINE(NI64, addInt64)(NI64 a, NI64 b);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
N_NIMCALL(PathComponent_9c1SIU9cO1wHcl09b703A9cDrg, getSymlinkFileKind_WoXOp8qmMec1P4MyA3LBKg)(NimStringDesc* path);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(TY_sM4lkSb7zS6F7OVMvW9cffQ*, sorted_m77sjnalzCFloHeNRrZi6w)(NimStringDesc** a, NI aLen_0, TY_kTj9c3SX9agxDQPZYwemi6ug cmp, SortOrder_8iBc6wlNqBa9cju9cUAhUAxA order);
N_NIMCALL(TY_sM4lkSb7zS6F7OVMvW9cffQ*, newSeq_9cL6dIz2UWtIh3FeS5x4hxA)(NI len);
N_NIMCALL(void, sort_9a7klSx0Yu33UIahhT1Of7Q)(NimStringDesc** a, NI aLen_0, TY_kTj9c3SX9agxDQPZYwemi6ug cmp, SortOrder_8iBc6wlNqBa9cju9cUAhUAxA order);
N_NIMCALL(void, merge_KHePwML9ba2tSMRLHxcf3EQ)(NimStringDesc** a, NI aLen_0, NimStringDesc** b, NI bLen_0, NI lo, NI m, NI hi, TY_kTj9c3SX9agxDQPZYwemi6ug cmp, SortOrder_8iBc6wlNqBa9cju9cUAhUAxA order);
N_NIMCALL(TY_9bzblIv39b19bLtyTzpVFK81g, X5BX5D__8MqzqF2HtONJUUXr9agvxPw)(Table_8Uf9bmzgz4A6eZu5h8HqdYA t, NimStringDesc* key);
N_NIMCALL(NI, main_tQeqwVpXaab7WPVl6lzEKA)(TY_sM4lkSb7zS6F7OVMvW9cffQ* args);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_TY_RAwOpb3u9aScvgKiZWJzF0w)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_CLOSURE(TY_sM4lkSb7zS6F7OVMvW9cffQ*, colonanonymous__ChU1s6jSzpU7YuzihtgRog)(void* ClE_0);
N_NIMCALL(NI, colonanonymous__S5IofPTyWKX7lz9cF19arKLg)(NimStringDesc* x, NimStringDesc* y);
N_NIMCALL(NI, cmp_xEnKsp9cfvO7Do9cTYXo8eJw)(NimStringDesc* x, NimStringDesc* y);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, nimInt64ToStr)(NI64 x);
N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
static N_NIMCALL(void, TM_4VP2PpByWPwo6q1BAjkSNA_27)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(TY_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NIMCALL(TY_sM4lkSb7zS6F7OVMvW9cffQ*, commandLineParams_WoBZMy8AVRATRE9bQuYWzCQ)(void);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_futureInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_futureDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, get_ext_listDatInit000)(void);
TNimType NTI_9bzblIv39b19bLtyTzpVFK81g_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_Aav8dQoMlCFnZRxA0IhTHQ_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_8Uf9bmzgz4A6eZu5h8HqdYA_;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
extern GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
TNimType NTI_M8m6n7N3H9cit7ldWho4FaQ_;
extern TNimType NTI_xHTZrq9aYs6boc9bCba0JbpQ_;
TNimType NTI_RAwOpb3u9aScvgKiZWJzF0w_;
TY_sM4lkSb7zS6F7OVMvW9cffQ* args_1CRbmb7rlA47daTA7nK63g;
STRING_LITERAL(TM_4VP2PpByWPwo6q1BAjkSNA_8, ".", 1);
STRING_LITERAL(TM_4VP2PpByWPwo6q1BAjkSNA_9, "..", 2);
STRING_LITERAL(TM_4VP2PpByWPwo6q1BAjkSNA_10, "noext", 5);
NIM_CONST TY_9bzblIv39b19bLtyTzpVFK81g TM_4VP2PpByWPwo6q1BAjkSNA_11 = {((NI) 0),
IL64(0)}
;
STRING_LITERAL(TM_4VP2PpByWPwo6q1BAjkSNA_12, "NOEXT:", 6);
STRING_LITERAL(TM_4VP2PpByWPwo6q1BAjkSNA_18, "directory(", 10);
STRING_LITERAL(TM_4VP2PpByWPwo6q1BAjkSNA_19, ") is not exists", 15);
STRING_LITERAL(TM_4VP2PpByWPwo6q1BAjkSNA_22, "ext\011count\011size", 14);
STRING_LITERAL(TM_4VP2PpByWPwo6q1BAjkSNA_24, "\011", 1);
STRING_LITERAL(TM_4VP2PpByWPwo6q1BAjkSNA_26, "len(a) == L seq modified while iterating over it", 48);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode) {
	NIM_BOOL result;
	nimfr_("isFilled", "tableimpl.nim")
	result = (NIM_BOOL)0;
	nimln_(18, "tableimpl.nim");
	nimln_(363, "system.nim");
	nimln_(18, "tableimpl.nim");
	result = !((hcode == ((NI) 0)));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash) {
	NI result;
	NI TM_4VP2PpByWPwo6q1BAjkSNA_3;
	nimfr_("nextTry", "tableimpl.nim")
	result = (NI)0;
	nimln_(28, "tableimpl.nim");
	TM_4VP2PpByWPwo6q1BAjkSNA_3 = addInt(h, ((NI) 1));
	result = (NI)((NI)(TM_4VP2PpByWPwo6q1BAjkSNA_3) & maxHash);
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, rawGet_9bnUTGHGTuHO3gGzrEbHDLgtables)(Table_8Uf9bmzgz4A6eZu5h8HqdYA t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI TM_4VP2PpByWPwo6q1BAjkSNA_4;
	nimfr_("rawGet", "tableimpl.nim")
{	result = (NI)0;
	nimln_(53, "tableimpl.nim");
	(*hc) = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	h = (NI)((*hc) & (t.data ? (t.data->Sup.len-1) : -1));
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T7_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T7_ = (NIM_BOOL)0;
			T7_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T7_) goto LA6;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T10_;
				T10_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T10_ = (t.data->data[h].Field0 == (*hc));
				if (!(T10_)) goto LA11_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T10_ = eqStrings(t.data->data[h].Field1, key);
				LA11_: ;
				if (!T10_) goto LA12_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA12_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA6: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_4VP2PpByWPwo6q1BAjkSNA_4 = subInt(((NI) -1), h);
	result = (NI)(TM_4VP2PpByWPwo6q1BAjkSNA_4);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, rawGetKnownHC_7x9ckJURtS0mgZKGnBgeeuAtables)(Table_8Uf9bmzgz4A6eZu5h8HqdYA t, NimStringDesc* key, NI hc) {
	NI result;
	NI h;
	NI TM_4VP2PpByWPwo6q1BAjkSNA_5;
	nimfr_("rawGetKnownHC", "tableimpl.nim")
{	result = (NI)0;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	h = (NI)(hc & (t.data ? (t.data->Sup.len-1) : -1));
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T3_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T3_ = (NIM_BOOL)0;
			T3_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T3_) goto LA2;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T6_;
				T6_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T6_ = (t.data->data[h].Field0 == hc);
				if (!(T6_)) goto LA7_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T6_ = eqStrings(t.data->data[h].Field1, key);
				LA7_: ;
				if (!T6_) goto LA8_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA8_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA2: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_4VP2PpByWPwo6q1BAjkSNA_5 = subInt(((NI) -1), h);
	result = (NI)(TM_4VP2PpByWPwo6q1BAjkSNA_5);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim")
	result = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim")
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim")
	nimln_(270, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(272, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(273, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NimStringDesc*, pop_9cDsfK2acP02vJ9bhxIE9caEAos)(TY_sM4lkSb7zS6F7OVMvW9cffQ** s) {
	NimStringDesc* result;
	NI L;
	NI TM_4VP2PpByWPwo6q1BAjkSNA_6;
	nimfr_("pop", "system.nim")
	result = (NimStringDesc*)0;
	nimln_(2298, "system.nim");
	TM_4VP2PpByWPwo6q1BAjkSNA_6 = subInt(((*s) ? (*s)->Sup.len : 0), ((NI) 1));
	L = (NI)(TM_4VP2PpByWPwo6q1BAjkSNA_6);
	nimln_(2299, "system.nim");
	if ((NU)(L) >= (NU)((*s)->Sup.len)) raiseIndexError();
	result = copyString((*s)->data[L]);
	nimln_(2300, "system.nim");
	(*s) = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) setLengthSeq(&((*s))->Sup, sizeof(NimStringDesc*), ((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}

static N_INLINE(NIM_BOOL, dirExists_wf0Ae3eLXw0lSNEFJMV3ogget_ext_list)(NimStringDesc* dir) {
	NIM_BOOL result;
	nimfr_("dirExists", "os.nim")
	result = (NIM_BOOL)0;
	nimln_(252, "os.nim");
	nimln_(253, "os.nim");
	result = nosexistsDir(dir);
	popFrame();
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(NI64, addInt64)(NI64 a, NI64 b) {
	NI64 result;
{	result = (NI64)0;
	result = (NI64)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (IL64(0) <= (NI64)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (IL64(0) <= (NI64)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

N_NIMCALL(void, get_ext_list_impl3_nKD3l9cckmFuiRs7pvUgtKQ)(NimStringDesc* startPath, Table_8Uf9bmzgz4A6eZu5h8HqdYA* Result) {
	nimfr_("get_ext_list_impl3", "get_ext_list.nim")
	nimln_(317, "tables.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_8Uf9bmzgz4A6eZu5h8HqdYA_));
	initTable_dOIBg8E67Yg7t5EIsoQ9aHA(((NI) 64), Result);
	{
		NimStringDesc* f;
		TY_sM4lkSb7zS6F7OVMvW9cffQ* volatile stack;
		NimStringDesc* T2_;
		f = (NimStringDesc*)0;
		nimln_(1046, "os.nim");
		stack = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 1);
		T2_ = (NimStringDesc*)0;
		T2_ = stack->data[0]; stack->data[0] = copyStringRC1(startPath);
		if (T2_) nimGCunrefNoCycle(T2_);
		{
			nimln_(1047, "os.nim");
			while (1) {
				if (!(((NI) 0) < (stack ? stack->Sup.len : 0))) goto LA4;
				{
					PathComponent_9c1SIU9cO1wHcl09b703A9cDrg k;
					NimStringDesc* p;
					NimStringDesc* colontmp_;
					DIR* d;
					k = (PathComponent_9c1SIU9cO1wHcl09b703A9cDrg)0;
					p = (NimStringDesc*)0;
					colontmp_ = (NimStringDesc*)0;
					nimln_(1048, "os.nim");
					colontmp_ = pop_9cDsfK2acP02vJ9bhxIE9caEAos((&stack));
					nimln_(998, "os.nim");
					d = opendir(colontmp_->data);
					nimln_(999, "os.nim");
					{
						TSafePoint TM_4VP2PpByWPwo6q1BAjkSNA_7;
						nimln_(363, "system.nim");
						nimln_(999, "os.nim");
						if (!!((d == NIM_NIL))) goto LA8_;
						nimln_(1000, "os.nim");
						pushSafePoint(&TM_4VP2PpByWPwo6q1BAjkSNA_7);
						TM_4VP2PpByWPwo6q1BAjkSNA_7.status = setjmp(TM_4VP2PpByWPwo6q1BAjkSNA_7.context);
						if (TM_4VP2PpByWPwo6q1BAjkSNA_7.status == 0) {
							{
								nimln_(1001, "os.nim");
								while (1) {
									{
										struct dirent* x;
										NimStringDesc* volatile y;
										nimln_(1002, "os.nim");
										x = readdir(d);
										nimln_(1003, "os.nim");
										{
											if (!(x == NIM_NIL)) goto LA16_;
											goto LA11;
										}
										LA16_: ;
										nimln_(1004, "os.nim");
										y = cstrToNimstr(((NCSTRING) ((*x).d_name)));
										nimln_(1005, "os.nim");
										{
											NIM_BOOL T20_;
											struct stat s;
											PathComponent_9c1SIU9cO1wHcl09b703A9cDrg volatile k_2;
											T20_ = (NIM_BOOL)0;
											nimln_(363, "system.nim");
											nimln_(1005, "os.nim");
											T20_ = !(eqStrings(y, ((NimStringDesc*) &TM_4VP2PpByWPwo6q1BAjkSNA_8)));
											if (!(T20_)) goto LA21_;
											nimln_(363, "system.nim");
											nimln_(1005, "os.nim");
											T20_ = !(eqStrings(y, ((NimStringDesc*) &TM_4VP2PpByWPwo6q1BAjkSNA_9)));
											LA21_: ;
											if (!T20_) goto LA22_;
											memset((void*)(&s), 0, sizeof(s));
											nimln_(1007, "os.nim");
											{
												if (!NIM_TRUE) goto LA26_;
												nimln_(1008, "os.nim");
												y = slash__lXoMhn1ZYc9cAJa9bfA61msg(colontmp_, y);
											}
											LA26_: ;
											nimln_(1009, "os.nim");
											k_2 = ((PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 0);
											nimln_(1012, "os.nim");
											{
												nimln_(363, "system.nim");
												nimln_(1012, "os.nim");
												if (!!(((*x).d_type == ((NI8) 0)))) goto LA30_;
												nimln_(1013, "os.nim");
												{
													if (!((*x).d_type == ((NI8) 4))) goto LA34_;
													k_2 = ((PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 2);
												}
												LA34_: ;
												nimln_(1014, "os.nim");
												{
													if (!((*x).d_type == ((NI8) 10))) goto LA38_;
													nimln_(1015, "os.nim");
													{
														NIM_BOOL T42_;
														T42_ = (NIM_BOOL)0;
														T42_ = dirExists_wf0Ae3eLXw0lSNEFJMV3ogget_ext_list(y);
														if (!T42_) goto LA43_;
														k_2 = ((PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 3);
													}
													goto LA40_;
													LA43_: ;
													{
														nimln_(1016, "os.nim");
														k_2 = ((PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 1);
													}
													LA40_: ;
												}
												LA38_: ;
												nimln_(1017, "os.nim");
												k = k_2;
												p = y;
												nimln_(1049, "os.nim");
												{
													nimln_(1027, "os.nim");
													if (!((5 &(1U<<((NU)(k)&7U)))!=0)) goto LA48_;
													nimln_(1050, "os.nim");
													switch (k) {
													case ((PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 0):
													case ((PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 1):
													{
														nimln_(1051, "os.nim");
														f = p;
														nimln_(63, "get_ext_list.nim");
														{
															NIM_BOOL T53_;
															TY_7q7q3E6Oj24ZNVJb9aonhAg T56_;
															NimStringDesc* _;
															NimStringDesc* __2;
															NimStringDesc* ext;
															NimStringDesc* volatile ext2;
															NI64 len;
															TY_9bzblIv39b19bLtyTzpVFK81g extInfo;
															TY_9bzblIv39b19bLtyTzpVFK81g* T71_;
															TY_9bzblIv39b19bLtyTzpVFK81g T72_;
															NI TM_4VP2PpByWPwo6q1BAjkSNA_13;
															NI64 TM_4VP2PpByWPwo6q1BAjkSNA_14;
															T53_ = (NIM_BOOL)0;
															T53_ = nosexistsFile(f);
															if (!T53_) goto LA54_;
															nimln_(64, "get_ext_list.nim");
															memset((void*)(&T56_), 0, sizeof(T56_));
															nossplitFile(f, (&T56_));
															_ = (NimStringDesc*)0;
															_ = T56_.Field0;
															__2 = (NimStringDesc*)0;
															__2 = T56_.Field1;
															ext = (NimStringDesc*)0;
															ext = T56_.Field2;
															nimln_(65, "get_ext_list.nim");
															ext2 = copyString(ext);
															nimln_(67, "get_ext_list.nim");
															{
																if (!((ext) && (ext)->Sup.len == 0)) goto LA59_;
																nimln_(68, "get_ext_list.nim");
																ext2 = copyString(((NimStringDesc*) &TM_4VP2PpByWPwo6q1BAjkSNA_10));
															}
															LA59_: ;
															nimln_(70, "get_ext_list.nim");
															{
																NIM_BOOL T63_;
																T63_ = (NIM_BOOL)0;
																T63_ = contains_mfFNyKdgINDteTqTsOLSEg((*Result), ext2);
																if (!(T63_ == NIM_FALSE)) goto LA64_;
																nimln_(71, "get_ext_list.nim");
																X5BX5Deq__3D7DhGkFWUzQM9auF2Bibyg(Result, ext2, TM_4VP2PpByWPwo6q1BAjkSNA_11);
															}
															LA64_: ;
															nimln_(72, "get_ext_list.nim");
															{
																NimStringDesc* T70_;
																if (!eqStrings(ext2, ((NimStringDesc*) &TM_4VP2PpByWPwo6q1BAjkSNA_10))) goto LA68_;
																nimln_(73, "get_ext_list.nim");
																T70_ = (NimStringDesc*)0;
																T70_ = rawNewString(f->Sup.len + 6);
appendString(T70_, ((NimStringDesc*) &TM_4VP2PpByWPwo6q1BAjkSNA_12));
appendString(T70_, f);
																printf("%s\012", T70_? (T70_)->data:"nil");
																fflush(stdout);
															}
															LA68_: ;
															nimln_(75, "get_ext_list.nim");
															len = nosgetFileSize(f);
															nimln_(76, "get_ext_list.nim");
															T71_ = (TY_9bzblIv39b19bLtyTzpVFK81g*)0;
															T71_ = X5BX5D__bMIBZN5tX7RVZpP2qmV9cZQ(Result, ext2);
															extInfo = (*T71_);
															nimln_(77, "get_ext_list.nim");
															TM_4VP2PpByWPwo6q1BAjkSNA_13 = addInt(extInfo.Field0, ((NI) 1));
															T72_.Field0 = (NI)(TM_4VP2PpByWPwo6q1BAjkSNA_13);
															TM_4VP2PpByWPwo6q1BAjkSNA_14 = addInt64(extInfo.Field1, len);
															T72_.Field1 = (NI64)(TM_4VP2PpByWPwo6q1BAjkSNA_14);
															X5BX5Deq__3D7DhGkFWUzQM9auF2Bibyg(Result, ext2, T72_);
														}
														LA54_: ;
													}
													break;
													case ((PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 2):
													case ((PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 3):
													{
														NimStringDesc* T74_;
														nimln_(1052, "os.nim");
														stack = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&(stack)->Sup, sizeof(NimStringDesc*));
														T74_ = (NimStringDesc*)0;
														T74_ = stack->data[stack->Sup.len]; stack->data[stack->Sup.len] = copyStringRC1(p);
														if (T74_) nimGCunrefNoCycle(T74_);
														++stack->Sup.len;
													}
													break;
													}
												}
												LA48_: ;
												nimln_(1018, "os.nim");
												goto LA13;
											}
											LA30_: ;
											nimln_(1020, "os.nim");
											{
												int T77_;
												T77_ = (int)0;
												T77_ = lstat(y->data, (&s));
												if (!(T77_ < ((NI32) 0))) goto LA78_;
												goto LA11;
											}
											LA78_: ;
											nimln_(1021, "os.nim");
											{
												NIM_BOOL T82_;
												T82_ = (NIM_BOOL)0;
												T82_ = S_ISDIR(s.st_mode);
												if (!T82_) goto LA83_;
												nimln_(1022, "os.nim");
												k_2 = ((PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 2);
											}
											goto LA80_;
											LA83_: ;
											{
												NIM_BOOL T86_;
												nimln_(1023, "os.nim");
												T86_ = (NIM_BOOL)0;
												T86_ = S_ISLNK(s.st_mode);
												if (!T86_) goto LA87_;
												nimln_(1024, "os.nim");
												k_2 = getSymlinkFileKind_WoXOp8qmMec1P4MyA3LBKg(y);
											}
											goto LA80_;
											LA87_: ;
											LA80_: ;
											nimln_(1025, "os.nim");
											k = k_2;
											p = y;
											nimln_(1049, "os.nim");
											{
												nimln_(1027, "os.nim");
												if (!((5 &(1U<<((NU)(k)&7U)))!=0)) goto LA91_;
												nimln_(1050, "os.nim");
												switch (k) {
												case ((PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 0):
												case ((PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 1):
												{
													nimln_(1051, "os.nim");
													f = p;
													nimln_(63, "get_ext_list.nim");
													{
														NIM_BOOL T96_;
														TY_7q7q3E6Oj24ZNVJb9aonhAg T99_;
														NimStringDesc* __3;
														NimStringDesc* __4;
														NimStringDesc* ext_2;
														NimStringDesc* volatile ext2_2;
														NI64 len_2;
														TY_9bzblIv39b19bLtyTzpVFK81g extInfo_2;
														TY_9bzblIv39b19bLtyTzpVFK81g* T114_;
														TY_9bzblIv39b19bLtyTzpVFK81g T115_;
														NI TM_4VP2PpByWPwo6q1BAjkSNA_15;
														NI64 TM_4VP2PpByWPwo6q1BAjkSNA_16;
														T96_ = (NIM_BOOL)0;
														T96_ = nosexistsFile(f);
														if (!T96_) goto LA97_;
														nimln_(64, "get_ext_list.nim");
														memset((void*)(&T99_), 0, sizeof(T99_));
														nossplitFile(f, (&T99_));
														__3 = (NimStringDesc*)0;
														__3 = T99_.Field0;
														__4 = (NimStringDesc*)0;
														__4 = T99_.Field1;
														ext_2 = (NimStringDesc*)0;
														ext_2 = T99_.Field2;
														nimln_(65, "get_ext_list.nim");
														ext2_2 = copyString(ext_2);
														nimln_(67, "get_ext_list.nim");
														{
															if (!((ext_2) && (ext_2)->Sup.len == 0)) goto LA102_;
															nimln_(68, "get_ext_list.nim");
															ext2_2 = copyString(((NimStringDesc*) &TM_4VP2PpByWPwo6q1BAjkSNA_10));
														}
														LA102_: ;
														nimln_(70, "get_ext_list.nim");
														{
															NIM_BOOL T106_;
															T106_ = (NIM_BOOL)0;
															T106_ = contains_mfFNyKdgINDteTqTsOLSEg((*Result), ext2_2);
															if (!(T106_ == NIM_FALSE)) goto LA107_;
															nimln_(71, "get_ext_list.nim");
															X5BX5Deq__3D7DhGkFWUzQM9auF2Bibyg(Result, ext2_2, TM_4VP2PpByWPwo6q1BAjkSNA_11);
														}
														LA107_: ;
														nimln_(72, "get_ext_list.nim");
														{
															NimStringDesc* T113_;
															if (!eqStrings(ext2_2, ((NimStringDesc*) &TM_4VP2PpByWPwo6q1BAjkSNA_10))) goto LA111_;
															nimln_(73, "get_ext_list.nim");
															T113_ = (NimStringDesc*)0;
															T113_ = rawNewString(f->Sup.len + 6);
appendString(T113_, ((NimStringDesc*) &TM_4VP2PpByWPwo6q1BAjkSNA_12));
appendString(T113_, f);
															printf("%s\012", T113_? (T113_)->data:"nil");
															fflush(stdout);
														}
														LA111_: ;
														nimln_(75, "get_ext_list.nim");
														len_2 = nosgetFileSize(f);
														nimln_(76, "get_ext_list.nim");
														T114_ = (TY_9bzblIv39b19bLtyTzpVFK81g*)0;
														T114_ = X5BX5D__bMIBZN5tX7RVZpP2qmV9cZQ(Result, ext2_2);
														extInfo_2 = (*T114_);
														nimln_(77, "get_ext_list.nim");
														TM_4VP2PpByWPwo6q1BAjkSNA_15 = addInt(extInfo_2.Field0, ((NI) 1));
														T115_.Field0 = (NI)(TM_4VP2PpByWPwo6q1BAjkSNA_15);
														TM_4VP2PpByWPwo6q1BAjkSNA_16 = addInt64(extInfo_2.Field1, len_2);
														T115_.Field1 = (NI64)(TM_4VP2PpByWPwo6q1BAjkSNA_16);
														X5BX5Deq__3D7DhGkFWUzQM9auF2Bibyg(Result, ext2_2, T115_);
													}
													LA97_: ;
												}
												break;
												case ((PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 2):
												case ((PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 3):
												{
													NimStringDesc* T117_;
													nimln_(1052, "os.nim");
													stack = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&(stack)->Sup, sizeof(NimStringDesc*));
													T117_ = (NimStringDesc*)0;
													T117_ = stack->data[stack->Sup.len]; stack->data[stack->Sup.len] = copyStringRC1(p);
													if (T117_) nimGCunrefNoCycle(T117_);
													++stack->Sup.len;
												}
												break;
												}
											}
											LA91_: ;
										}
										LA22_: ;
									} LA13: ;
								}
							} LA11: ;
							popSafePoint();
						}
						else {
							popSafePoint();
							setFrame((TFrame*)&FR_);
						}
						{
							int T120_;
							nimln_(1000, "os.nim");
							T120_ = (int)0;
							T120_ = closedir(d);
						}
						if (TM_4VP2PpByWPwo6q1BAjkSNA_7.status != 0) reraiseException();
					}
					LA8_: ;
				}
			} LA4: ;
		}
	}
	popFrame();
}
static N_NIMCALL(void, Marker_TY_RAwOpb3u9aScvgKiZWJzF0w)(void* p, NI op) {
	Env_get_ext_listdotnim__M8m6n7N3H9cit7ldWho4FaQ* a;
	a = (Env_get_ext_listdotnim__M8m6n7N3H9cit7ldWho4FaQ*)p;
	nimGCvisit((void*)(*a).ret1.data, op);
}

N_CLOSURE(TY_sM4lkSb7zS6F7OVMvW9cffQ*, colonanonymous__ChU1s6jSzpU7YuzihtgRog)(void* ClE_0) {
	TY_sM4lkSb7zS6F7OVMvW9cffQ* result;
	Env_get_ext_listdotnim__M8m6n7N3H9cit7ldWho4FaQ* colonenvP_;
	nimfr_(":anonymous", "get_ext_list.nim")
	result = (TY_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	colonenvP_ = (Env_get_ext_listdotnim__M8m6n7N3H9cit7ldWho4FaQ*) ClE_0;
	nimln_(101, "get_ext_list.nim");
	result = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
	{
		NimStringDesc* k;
		k = (NimStringDesc*)0;
		{
			NI h;
			NI colontmp_;
			NI res;
			h = (NI)0;
			colontmp_ = (NI)0;
			nimln_(255, "tables.nim");
			colontmp_ = ((*colonenvP_).ret1.data ? ((*colonenvP_).ret1.data->Sup.len-1) : -1);
			nimln_(1955, "system.nim");
			res = ((NI) 0);
			{
				nimln_(1956, "system.nim");
				while (1) {
					NI TM_4VP2PpByWPwo6q1BAjkSNA_20;
					if (!(res <= colontmp_)) goto LA4;
					nimln_(1957, "system.nim");
					h = res;
					nimln_(256, "tables.nim");
					{
						NIM_BOOL T7_;
						NimStringDesc* T10_;
						if ((NU)(h) >= (NU)((*colonenvP_).ret1.data->Sup.len)) raiseIndexError();
						T7_ = (NIM_BOOL)0;
						T7_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables((*colonenvP_).ret1.data->data[h].Field0);
						if (!T7_) goto LA8_;
						if ((NU)(h) >= (NU)((*colonenvP_).ret1.data->Sup.len)) raiseIndexError();
						k = (*colonenvP_).ret1.data->data[h].Field1;
						nimln_(101, "get_ext_list.nim");
						result = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&(result)->Sup, sizeof(NimStringDesc*));
						T10_ = (NimStringDesc*)0;
						T10_ = result->data[result->Sup.len]; result->data[result->Sup.len] = copyStringRC1(k);
						if (T10_) nimGCunrefNoCycle(T10_);
						++result->Sup.len;
					}
					LA8_: ;
					nimln_(1976, "system.nim");
					TM_4VP2PpByWPwo6q1BAjkSNA_20 = addInt(res, ((NI) 1));
					res = (NI)(TM_4VP2PpByWPwo6q1BAjkSNA_20);
				} LA4: ;
			}
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NI, colonanonymous__S5IofPTyWKX7lz9cF19arKLg)(NimStringDesc* x, NimStringDesc* y) {
	NI result;
	NimStringDesc* it;
	NimStringDesc* a;
	NimStringDesc* b;
	nimfr_(":anonymous", "algorithm.nim")
	result = (NI)0;
	nimln_(237, "algorithm.nim");
	it = copyString(x);
	nimln_(238, "algorithm.nim");
	a = it;
	nimln_(239, "algorithm.nim");
	it = copyString(y);
	nimln_(240, "algorithm.nim");
	b = it;
	nimln_(241, "algorithm.nim");
	result = cmp_xEnKsp9cfvO7Do9cTYXo8eJw(a, b);
	popFrame();
	return result;
}

N_NIMCALL(NI, main_tQeqwVpXaab7WPVl6lzEKA)(TY_sM4lkSb7zS6F7OVMvW9cffQ* args) {
	NI result;
	Env_get_ext_listdotnim__M8m6n7N3H9cit7ldWho4FaQ* colonenv_;
	NimStringDesc* path;
	TY_sM4lkSb7zS6F7OVMvW9cffQ* keys;
	TY_jGa0TDlm1RK7NwnvKCTNkQ T11_;
	nimfr_("main", "get_ext_list.nim")
{	result = (NI)0;
	colonenv_ = (Env_get_ext_listdotnim__M8m6n7N3H9cit7ldWho4FaQ*)0;
	nimln_(80, "get_ext_list.nim");
	colonenv_ = (Env_get_ext_listdotnim__M8m6n7N3H9cit7ldWho4FaQ*) newObj((&NTI_RAwOpb3u9aScvgKiZWJzF0w_), sizeof(Env_get_ext_listdotnim__M8m6n7N3H9cit7ldWho4FaQ));
	nimln_(82, "get_ext_list.nim");
	result = ((NI) 1);
	nimln_(85, "get_ext_list.nim");
	nimln_(86, "get_ext_list.nim");
	{
		if (!((args ? args->Sup.len : 0) == ((NI) 1))) goto LA3_;
		if ((NU)(((NI) 0)) >= (NU)(args->Sup.len)) raiseIndexError();
		path = args->data[((NI) 0)];
	}
	goto LA1_;
	LA3_: ;
	{
		path = copyString(((NimStringDesc*) &TM_4VP2PpByWPwo6q1BAjkSNA_8));
	}
	LA1_: ;
	nimln_(90, "get_ext_list.nim");
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nosexistsDir(path);
		if (!(T8_ == NIM_FALSE)) goto LA9_;
		nimln_(91, "get_ext_list.nim");
		printf("%s%s%s\012", ((NimStringDesc*) &TM_4VP2PpByWPwo6q1BAjkSNA_18)? (((NimStringDesc*) &TM_4VP2PpByWPwo6q1BAjkSNA_18))->data:"nil", path? (path)->data:"nil", ((NimStringDesc*) &TM_4VP2PpByWPwo6q1BAjkSNA_19)? (((NimStringDesc*) &TM_4VP2PpByWPwo6q1BAjkSNA_19))->data:"nil");
		fflush(stdout);
		nimln_(93, "get_ext_list.nim");
		goto BeforeRet_;
	}
	LA9_: ;
	nimln_(98, "get_ext_list.nim");
	chckNil((void*)(&(*colonenv_).ret1));
	genericReset((void*)(&(*colonenv_).ret1), (&NTI_8Uf9bmzgz4A6eZu5h8HqdYA_));
	get_ext_list_impl3_nKD3l9cckmFuiRs7pvUgtKQ(path, (&(*colonenv_).ret1));
	nimln_(101, "get_ext_list.nim");
	memset((void*)(&T11_), 0, sizeof(T11_));
	T11_.ClP_0 = colonanonymous__ChU1s6jSzpU7YuzihtgRog; T11_.ClE_0 = colonenv_;
	keys = T11_.ClE_0? T11_.ClP_0(T11_.ClE_0):((TM_4VP2PpByWPwo6q1BAjkSNA_21)(T11_.ClP_0))();
	nimln_(104, "get_ext_list.nim");
	printf("%s\012", ((NimStringDesc*) &TM_4VP2PpByWPwo6q1BAjkSNA_22)? (((NimStringDesc*) &TM_4VP2PpByWPwo6q1BAjkSNA_22))->data:"nil");
	fflush(stdout);
	{
		NimStringDesc* k;
		TY_sM4lkSb7zS6F7OVMvW9cffQ* colontmp_;
		TY_sM4lkSb7zS6F7OVMvW9cffQ* result_2;
		TY_kTj9c3SX9agxDQPZYwemi6ug T13_;
		NI i;
		NI L;
		k = (NimStringDesc*)0;
		colontmp_ = (TY_sM4lkSb7zS6F7OVMvW9cffQ*)0;
		nimln_(107, "get_ext_list.nim");
		nimln_(236, "algorithm.nim");
		memset((void*)(&T13_), 0, sizeof(T13_));
		T13_.ClP_0 = ((TM_4VP2PpByWPwo6q1BAjkSNA_23) (colonanonymous__S5IofPTyWKX7lz9cF19arKLg)); T13_.ClE_0 = NIM_NIL;
		result_2 = sorted_m77sjnalzCFloHeNRrZi6w(keys->data, keys->Sup.len, T13_, ((SortOrder_8iBc6wlNqBa9cju9cUAhUAxA) 1));
		colontmp_ = result_2;
		nimln_(3580, "system.nim");
		i = ((NI) 0);
		nimln_(3581, "system.nim");
		L = (colontmp_ ? colontmp_->Sup.len : 0);
		{
			nimln_(3582, "system.nim");
			while (1) {
				TY_9bzblIv39b19bLtyTzpVFK81g T16_;
				NimStringDesc* T17_;
				TY_9bzblIv39b19bLtyTzpVFK81g T18_;
				NimStringDesc* T19_;
				NI TM_4VP2PpByWPwo6q1BAjkSNA_25;
				if (!(i < L)) goto LA15;
				nimln_(3583, "system.nim");
				if ((NU)(i) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
				k = colontmp_->data[i];
				nimln_(108, "get_ext_list.nim");
				T16_ = X5BX5D__8MqzqF2HtONJUUXr9agvxPw((*colonenv_).ret1, k);
				T17_ = (NimStringDesc*)0;
				T17_ = nimIntToStr(T16_.Field0);
				T18_ = X5BX5D__8MqzqF2HtONJUUXr9agvxPw((*colonenv_).ret1, k);
				T19_ = (NimStringDesc*)0;
				T19_ = nimInt64ToStr(T18_.Field1);
				printf("%s%s%s%s%s\012", k? (k)->data:"nil", ((NimStringDesc*) &TM_4VP2PpByWPwo6q1BAjkSNA_24)? (((NimStringDesc*) &TM_4VP2PpByWPwo6q1BAjkSNA_24))->data:"nil", T17_? (T17_)->data:"nil", ((NimStringDesc*) &TM_4VP2PpByWPwo6q1BAjkSNA_24)? (((NimStringDesc*) &TM_4VP2PpByWPwo6q1BAjkSNA_24))->data:"nil", T19_? (T19_)->data:"nil");
				fflush(stdout);
				nimln_(3584, "system.nim");
				TM_4VP2PpByWPwo6q1BAjkSNA_25 = addInt(i, ((NI) 1));
				i = (NI)(TM_4VP2PpByWPwo6q1BAjkSNA_25);
				nimln_(3585, "system.nim");
				{
					if (!!(((colontmp_ ? colontmp_->Sup.len : 0) == L))) goto LA22_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4VP2PpByWPwo6q1BAjkSNA_26));
				}
				LA22_: ;
			} LA15: ;
		}
	}
	nimln_(111, "get_ext_list.nim");
	result = ((NI) 0);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, TM_4VP2PpByWPwo6q1BAjkSNA_27)(void) {
	nimGCvisit((void*)args_1CRbmb7rlA47daTA7nK63g, 0);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim")
	nimln_(288, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(363, "system.nim");
		nimln_(288, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(289, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(290, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(291, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(363, "system.nim");
		nimln_(291, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(292, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(293, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(294, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(295, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_timesDatInit000();
	stdlib_posixDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	stdlib_hashesDatInit000();
	stdlib_tablesDatInit000();
	stdlib_macrosDatInit000();
	stdlib_futureDatInit000();
	get_ext_listDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_timesInit000();
	stdlib_posixInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	stdlib_hashesInit000();
	stdlib_tablesInit000();
	stdlib_macrosInit000();
	stdlib_futureInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	NI T1_;
	nimfr_("get_ext_list", "get_ext_list.nim")
nimRegisterGlobalMarker(TM_4VP2PpByWPwo6q1BAjkSNA_27);
	nimln_(115, "get_ext_list.nim");
	asgnRefNoCycle((void**) (&args_1CRbmb7rlA47daTA7nK63g), commandLineParams_WoBZMy8AVRATRE9bQuYWzCQ());
	nimln_(117, "get_ext_list.nim");
	T1_ = (NI)0;
	T1_ = main_tQeqwVpXaab7WPVl6lzEKA(args_1CRbmb7rlA47daTA7nK63g);
	exit(T1_);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, get_ext_listDatInit000)(void) {
static TNimNode* TM_4VP2PpByWPwo6q1BAjkSNA_2[2];
static TNimNode* TM_4VP2PpByWPwo6q1BAjkSNA_17[2];
static TNimNode TM_4VP2PpByWPwo6q1BAjkSNA_0[6];
NTI_9bzblIv39b19bLtyTzpVFK81g_.size = sizeof(TY_9bzblIv39b19bLtyTzpVFK81g);
NTI_9bzblIv39b19bLtyTzpVFK81g_.kind = 18;
NTI_9bzblIv39b19bLtyTzpVFK81g_.base = 0;
NTI_9bzblIv39b19bLtyTzpVFK81g_.flags = 3;
TM_4VP2PpByWPwo6q1BAjkSNA_2[0] = &TM_4VP2PpByWPwo6q1BAjkSNA_0[1];
TM_4VP2PpByWPwo6q1BAjkSNA_0[1].kind = 1;
TM_4VP2PpByWPwo6q1BAjkSNA_0[1].offset = offsetof(TY_9bzblIv39b19bLtyTzpVFK81g, Field0);
TM_4VP2PpByWPwo6q1BAjkSNA_0[1].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4VP2PpByWPwo6q1BAjkSNA_0[1].name = "Field0";
TM_4VP2PpByWPwo6q1BAjkSNA_2[1] = &TM_4VP2PpByWPwo6q1BAjkSNA_0[2];
TM_4VP2PpByWPwo6q1BAjkSNA_0[2].kind = 1;
TM_4VP2PpByWPwo6q1BAjkSNA_0[2].offset = offsetof(TY_9bzblIv39b19bLtyTzpVFK81g, Field1);
TM_4VP2PpByWPwo6q1BAjkSNA_0[2].typ = (&NTI_Aav8dQoMlCFnZRxA0IhTHQ_);
TM_4VP2PpByWPwo6q1BAjkSNA_0[2].name = "Field1";
TM_4VP2PpByWPwo6q1BAjkSNA_0[0].len = 2; TM_4VP2PpByWPwo6q1BAjkSNA_0[0].kind = 2; TM_4VP2PpByWPwo6q1BAjkSNA_0[0].sons = &TM_4VP2PpByWPwo6q1BAjkSNA_2[0];
NTI_9bzblIv39b19bLtyTzpVFK81g_.node = &TM_4VP2PpByWPwo6q1BAjkSNA_0[0];
NTI_M8m6n7N3H9cit7ldWho4FaQ_.size = sizeof(Env_get_ext_listdotnim__M8m6n7N3H9cit7ldWho4FaQ);
NTI_M8m6n7N3H9cit7ldWho4FaQ_.kind = 18;
NTI_M8m6n7N3H9cit7ldWho4FaQ_.base = 0;
NTI_M8m6n7N3H9cit7ldWho4FaQ_.flags = 2;
TM_4VP2PpByWPwo6q1BAjkSNA_17[0] = &TM_4VP2PpByWPwo6q1BAjkSNA_0[4];
TM_4VP2PpByWPwo6q1BAjkSNA_0[4].kind = 1;
TM_4VP2PpByWPwo6q1BAjkSNA_0[4].offset = offsetof(Env_get_ext_listdotnim__M8m6n7N3H9cit7ldWho4FaQ, colonstate_);
TM_4VP2PpByWPwo6q1BAjkSNA_0[4].typ = (&NTI_xHTZrq9aYs6boc9bCba0JbpQ_);
TM_4VP2PpByWPwo6q1BAjkSNA_0[4].name = ":state";
TM_4VP2PpByWPwo6q1BAjkSNA_17[1] = &TM_4VP2PpByWPwo6q1BAjkSNA_0[5];
TM_4VP2PpByWPwo6q1BAjkSNA_0[5].kind = 1;
TM_4VP2PpByWPwo6q1BAjkSNA_0[5].offset = offsetof(Env_get_ext_listdotnim__M8m6n7N3H9cit7ldWho4FaQ, ret1);
TM_4VP2PpByWPwo6q1BAjkSNA_0[5].typ = (&NTI_8Uf9bmzgz4A6eZu5h8HqdYA_);
TM_4VP2PpByWPwo6q1BAjkSNA_0[5].name = "ret1";
TM_4VP2PpByWPwo6q1BAjkSNA_0[3].len = 2; TM_4VP2PpByWPwo6q1BAjkSNA_0[3].kind = 2; TM_4VP2PpByWPwo6q1BAjkSNA_0[3].sons = &TM_4VP2PpByWPwo6q1BAjkSNA_17[0];
NTI_M8m6n7N3H9cit7ldWho4FaQ_.node = &TM_4VP2PpByWPwo6q1BAjkSNA_0[3];
NTI_RAwOpb3u9aScvgKiZWJzF0w_.size = sizeof(Env_get_ext_listdotnim__M8m6n7N3H9cit7ldWho4FaQ*);
NTI_RAwOpb3u9aScvgKiZWJzF0w_.kind = 22;
NTI_RAwOpb3u9aScvgKiZWJzF0w_.base = (&NTI_M8m6n7N3H9cit7ldWho4FaQ_);
NTI_RAwOpb3u9aScvgKiZWJzF0w_.flags = 2;
NTI_RAwOpb3u9aScvgKiZWJzF0w_.marker = Marker_TY_RAwOpb3u9aScvgKiZWJzF0w;
}

