/* Generated by Nim Compiler v0.17.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/opt/apps/nim/nim-0.17.0/lib -o /mnt/pcie/workspaces/workspace-nim/get_ext_list/src/nimcache/stdlib_algorithm.o /mnt/pcie/workspaces/workspace-nim/get_ext_list/src/nimcache/stdlib_algorithm.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef linux
#undef near
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY_sM4lkSb7zS6F7OVMvW9cffQ TY_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct Cell_1zcF9cV8XIAtbN8h5HRUB8g Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct TNimType TNimType;
typedef struct CellSeq_Axo1XVm9aaQueTOldv8le5w CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct GcHeap_1TRH1TZMaVZTnLNcIHuNFQ GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct GcStack_7fytPA5bBsob6See21YMRA GcStack_7fytPA5bBsob6See21YMRA;
typedef struct MemRegion_x81NhDv59b8ercDZ9bi85jyg MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct SmallChunk_tXn60W2f8h3jgAYdEmy5NQ SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct LLChunk_XsENErzHIZV9bhvyJx56wGw LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct BigChunk_Rv9c70Uhp2TytkX7eH78qEg BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct IntSet_EZObFrE3NC9bIb3YMkY9crZA IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct AvlNode_IaqjtwKhxLEpvDS9bct9blEw AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct TY_ujsjpB2O9cjj3uDHsXbnSzg TY_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct GcStat_0RwLoVBHZPfUAcLczmfQAg GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct CellSet_jG87P0AI9aZtss9ccTYBIISQ CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct PageDesc_fublkgIY4LG3mT51LU2WHg PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct TNimNode TNimNode;
typedef struct BaseChunk_Sdq7WpT6qAH858F5ZEdG3w BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct FreeCell_u6M5LHprqzkn9axr04yg9bGQ FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef NU8 SortOrder_8iBc6wlNqBa9cju9cUAhUAxA;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef struct {
N_NIMCALL_PTR(NI, ClP_0) (NimStringDesc* x, NimStringDesc* y, void* ClE_0);
void* ClE_0;
} TY_kTj9c3SX9agxDQPZYwemi6ug;
struct  Cell_1zcF9cV8XIAtbN8h5HRUB8g  {
NI refcount;
TNimType* typ;
};
struct  GcStack_7fytPA5bBsob6See21YMRA  {
void* bottom;
};
struct  CellSeq_Axo1XVm9aaQueTOldv8le5w  {
NI len;
NI cap;
Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* TY_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef Trunk_W0r8S0Y3UGke6T9bIUWnnuw* TY_lh2A89ahMmYg9bCmpVaplLbA[256];
struct  IntSet_EZObFrE3NC9bIb3YMkY9crZA  {
TY_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef AvlNode_IaqjtwKhxLEpvDS9bct9blEw* TY_0aOLqZchNi8nWtMTi8ND8w[2];
struct  AvlNode_IaqjtwKhxLEpvDS9bct9blEw  {
TY_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct TY_ujsjpB2O9cjj3uDHsXbnSzg {
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef TY_ujsjpB2O9cjj3uDHsXbnSzg TY_LzOv2eCDGiceMKQstCLmhw[30];
struct  HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg  {
NI len;
TY_LzOv2eCDGiceMKQstCLmhw chunks;
HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct  MemRegion_x81NhDv59b8ercDZ9bi85jyg  {
NI minLargeObj;
NI maxLargeObj;
TY_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct  GcStat_0RwLoVBHZPfUAcLczmfQAg  {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct  CellSet_jG87P0AI9aZtss9ccTYBIISQ  {
NI counter;
NI max;
PageDesc_fublkgIY4LG3mT51LU2WHg* head;
PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct  GcHeap_1TRH1TZMaVZTnLNcIHuNFQ  {
GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
typedef NU8 TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct  TNimType  {
NI size;
TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CLOSURE_PTR(NI, TM_JdC9c6SaUkvO1XjYuWP1JWQ_11) (NimStringDesc* x, NimStringDesc* y);
typedef N_CLOSURE_PTR(NI, TM_JdC9c6SaUkvO1XjYuWP1JWQ_15) (NimStringDesc* x, NimStringDesc* y);
struct  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w  {
NI prevSize;
NI size;
};
struct  SmallChunk_tXn60W2f8h3jgAYdEmy5NQ  {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct  LLChunk_XsENErzHIZV9bhvyJx56wGw  {
NI size;
NI acc;
LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct  BigChunk_Rv9c70Uhp2TytkX7eH78qEg  {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI TY_9a8QARi5WsUggNU9bom7kzTQ[8];
struct  Trunk_W0r8S0Y3UGke6T9bIUWnnuw  {
Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  PageDesc_fublkgIY4LG3mT51LU2WHg  {
PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  FreeCell_u6M5LHprqzkn9axr04yg9bGQ  {
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct TY_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
static N_INLINE(NI, star__mciSqxUij8SrsZknIQqvwwalgorithm)(NI x, SortOrder_8iBc6wlNqBa9cju9cUAhUAxA order);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, reverse_XQiN4wExsmIg8NFBmG3ObA)(NimStringDesc** a, NI aLen_0, NI first, NI last);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(TY_sM4lkSb7zS6F7OVMvW9cffQ*, newSeq_9cL6dIz2UWtIh3FeS5x4hxA)(NI len);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(CellSeq_Axo1XVm9aaQueTOldv8le5w* s, Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, sort_9a7klSx0Yu33UIahhT1Of7Q)(NimStringDesc** a, NI aLen_0, TY_kTj9c3SX9agxDQPZYwemi6ug cmp, SortOrder_8iBc6wlNqBa9cju9cUAhUAxA order);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, merge_KHePwML9ba2tSMRLHxcf3EQ)(NimStringDesc** a, NI aLen_0, NimStringDesc** b, NI bLen_0, NI lo, NI m, NI hi, TY_kTj9c3SX9agxDQPZYwemi6ug cmp, SortOrder_8iBc6wlNqBa9cju9cUAhUAxA order);
N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NIMCALL(NI, mulInt)(NI a, NI b);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
STRING_LITERAL(TM_JdC9c6SaUkvO1XjYuWP1JWQ_12, "j <= m ", 7);

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NI, star__mciSqxUij8SrsZknIQqvwwalgorithm)(NI x, SortOrder_8iBc6wlNqBa9cju9cUAhUAxA order) {
	NI result;
	NI y;
	NI TM_JdC9c6SaUkvO1XjYuWP1JWQ_2;
	NI TM_JdC9c6SaUkvO1XjYuWP1JWQ_3;
	nimfr_("*", "algorithm.nim")
	result = (NI)0;
	nimln_(24, "algorithm.nim");
	TM_JdC9c6SaUkvO1XjYuWP1JWQ_2 = subInt(((NI) (order)), ((NI) 1));
	y = (NI)(TM_JdC9c6SaUkvO1XjYuWP1JWQ_2);
	nimln_(25, "algorithm.nim");
	TM_JdC9c6SaUkvO1XjYuWP1JWQ_3 = subInt((NI)(x ^ ((NI) (y))), ((NI) (y)));
	result = (NI)(TM_JdC9c6SaUkvO1XjYuWP1JWQ_3);
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(void, reverse_XQiN4wExsmIg8NFBmG3ObA)(NimStringDesc** a, NI aLen_0, NI first, NI last) {
	NI x;
	NI y;
	nimfr_("reverse", "algorithm.nim")
	nimln_(40, "algorithm.nim");
	x = first;
	nimln_(41, "algorithm.nim");
	y = last;
	{
		nimln_(42, "algorithm.nim");
		while (1) {
			NimStringDesc* T3_;
			NI TM_JdC9c6SaUkvO1XjYuWP1JWQ_4;
			NI TM_JdC9c6SaUkvO1XjYuWP1JWQ_5;
			if (!(((NI) (x)) < ((NI) (y)))) goto LA2;
			nimln_(43, "algorithm.nim");
			T3_ = (NimStringDesc*)0;
			if ((NU)(x) >= (NU)(aLen_0)) raiseIndexError();
			if ((NU)(y) >= (NU)(aLen_0)) raiseIndexError();
			T3_ = a[x];
			unsureAsgnRef((void**) (&a[x]), a[y]);
			unsureAsgnRef((void**) (&a[y]), T3_);
			nimln_(44, "algorithm.nim");
			TM_JdC9c6SaUkvO1XjYuWP1JWQ_4 = subInt(y, ((NI) 1));
			if (TM_JdC9c6SaUkvO1XjYuWP1JWQ_4 < 0 || TM_JdC9c6SaUkvO1XjYuWP1JWQ_4 > IL64(9223372036854775807)) raiseOverflow();
			y = (NI)(TM_JdC9c6SaUkvO1XjYuWP1JWQ_4);
			nimln_(45, "algorithm.nim");
			TM_JdC9c6SaUkvO1XjYuWP1JWQ_5 = addInt(x, ((NI) 1));
			if (TM_JdC9c6SaUkvO1XjYuWP1JWQ_5 < 0 || TM_JdC9c6SaUkvO1XjYuWP1JWQ_5 > IL64(9223372036854775807)) raiseOverflow();
			x = (NI)(TM_JdC9c6SaUkvO1XjYuWP1JWQ_5);
		} LA2: ;
	}
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(void, reverse_LoixoqZetR6FfezoPedx8w)(NimStringDesc** a, NI aLen_0) {
	nimfr_("reverse", "algorithm.nim")
	nimln_(49, "algorithm.nim");
	reverse_XQiN4wExsmIg8NFBmG3ObA(a, aLen_0, ((NI) 0), ((NI)chckRange(((((NI) 0) >= (aLen_0-1)) ? ((NI) 0) : (aLen_0-1)), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
}

static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim")
	result = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim")
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim")
	nimln_(270, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(272, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(273, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
		raiseOverflow();
	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(void, merge_KHePwML9ba2tSMRLHxcf3EQ)(NimStringDesc** a, NI aLen_0, NimStringDesc** b, NI bLen_0, NI lo, NI m, NI hi, TY_kTj9c3SX9agxDQPZYwemi6ug cmp, SortOrder_8iBc6wlNqBa9cju9cUAhUAxA order) {
	NI j;
	NI bb;
	NI i;
	NI k;
	nimfr_("merge", "algorithm.nim")
{	nimln_(130, "algorithm.nim");
	{
		NI TM_JdC9c6SaUkvO1XjYuWP1JWQ_10;
		NI T3_;
		NI T4_;
		if ((NU)(m) >= (NU)(aLen_0)) raiseIndexError();
		TM_JdC9c6SaUkvO1XjYuWP1JWQ_10 = addInt(m, ((NI) 1));
		if ((NU)((NI)(TM_JdC9c6SaUkvO1XjYuWP1JWQ_10)) >= (NU)(aLen_0)) raiseIndexError();
		T3_ = (NI)0;
		T3_ = cmp.ClE_0? cmp.ClP_0(a[m], a[(NI)(TM_JdC9c6SaUkvO1XjYuWP1JWQ_10)], cmp.ClE_0):((TM_JdC9c6SaUkvO1XjYuWP1JWQ_11)(cmp.ClP_0))(a[m], a[(NI)(TM_JdC9c6SaUkvO1XjYuWP1JWQ_10)]);
		T4_ = (NI)0;
		T4_ = star__mciSqxUij8SrsZknIQqvwwalgorithm(T3_, order);
		if (!(T4_ <= ((NI) 0))) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	nimln_(131, "algorithm.nim");
	j = lo;
	nimln_(133, "algorithm.nim");
	{
		if (!!((j <= m))) goto LA9_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_JdC9c6SaUkvO1XjYuWP1JWQ_12));
	}
	LA9_: ;
	nimln_(135, "algorithm.nim");
	bb = ((NI) 0);
	{
		nimln_(136, "algorithm.nim");
		while (1) {
			NI TM_JdC9c6SaUkvO1XjYuWP1JWQ_13;
			NI TM_JdC9c6SaUkvO1XjYuWP1JWQ_14;
			if (!(j <= m)) goto LA12;
			if ((NU)(bb) >= (NU)(bLen_0)) raiseIndexError();
			nimln_(137, "algorithm.nim");
			if ((NU)(j) >= (NU)(aLen_0)) raiseIndexError();
			unsureAsgnRef((void**) (&b[bb]), a[j]);
			nimln_(138, "algorithm.nim");
			TM_JdC9c6SaUkvO1XjYuWP1JWQ_13 = addInt(bb, ((NI) 1));
			bb = (NI)(TM_JdC9c6SaUkvO1XjYuWP1JWQ_13);
			nimln_(139, "algorithm.nim");
			TM_JdC9c6SaUkvO1XjYuWP1JWQ_14 = addInt(j, ((NI) 1));
			j = (NI)(TM_JdC9c6SaUkvO1XjYuWP1JWQ_14);
		} LA12: ;
	}
	nimln_(143, "algorithm.nim");
	i = ((NI) 0);
	nimln_(144, "algorithm.nim");
	k = lo;
	{
		nimln_(146, "algorithm.nim");
		while (1) {
			NIM_BOOL T15_;
			NI TM_JdC9c6SaUkvO1XjYuWP1JWQ_18;
			T15_ = (NIM_BOOL)0;
			T15_ = (k < j);
			if (!(T15_)) goto LA16_;
			T15_ = (j <= hi);
			LA16_: ;
			if (!T15_) goto LA14;
			nimln_(147, "algorithm.nim");
			{
				NI T19_;
				NI T20_;
				NI TM_JdC9c6SaUkvO1XjYuWP1JWQ_16;
				if ((NU)(i) >= (NU)(bLen_0)) raiseIndexError();
				if ((NU)(j) >= (NU)(aLen_0)) raiseIndexError();
				T19_ = (NI)0;
				T19_ = cmp.ClE_0? cmp.ClP_0(b[i], a[j], cmp.ClE_0):((TM_JdC9c6SaUkvO1XjYuWP1JWQ_15)(cmp.ClP_0))(b[i], a[j]);
				T20_ = (NI)0;
				T20_ = star__mciSqxUij8SrsZknIQqvwwalgorithm(T19_, order);
				if (!(T20_ <= ((NI) 0))) goto LA21_;
				if ((NU)(k) >= (NU)(aLen_0)) raiseIndexError();
				nimln_(148, "algorithm.nim");
				if ((NU)(i) >= (NU)(bLen_0)) raiseIndexError();
				unsureAsgnRef((void**) (&a[k]), b[i]);
				nimln_(149, "algorithm.nim");
				TM_JdC9c6SaUkvO1XjYuWP1JWQ_16 = addInt(i, ((NI) 1));
				i = (NI)(TM_JdC9c6SaUkvO1XjYuWP1JWQ_16);
			}
			goto LA17_;
			LA21_: ;
			{
				NI TM_JdC9c6SaUkvO1XjYuWP1JWQ_17;
				if ((NU)(k) >= (NU)(aLen_0)) raiseIndexError();
				nimln_(151, "algorithm.nim");
				if ((NU)(j) >= (NU)(aLen_0)) raiseIndexError();
				unsureAsgnRef((void**) (&a[k]), a[j]);
				nimln_(152, "algorithm.nim");
				TM_JdC9c6SaUkvO1XjYuWP1JWQ_17 = addInt(j, ((NI) 1));
				j = (NI)(TM_JdC9c6SaUkvO1XjYuWP1JWQ_17);
			}
			LA17_: ;
			nimln_(153, "algorithm.nim");
			TM_JdC9c6SaUkvO1XjYuWP1JWQ_18 = addInt(k, ((NI) 1));
			k = (NI)(TM_JdC9c6SaUkvO1XjYuWP1JWQ_18);
		} LA14: ;
	}
	{
		nimln_(156, "algorithm.nim");
		while (1) {
			NI TM_JdC9c6SaUkvO1XjYuWP1JWQ_19;
			NI TM_JdC9c6SaUkvO1XjYuWP1JWQ_20;
			if (!(k < j)) goto LA25;
			if ((NU)(k) >= (NU)(aLen_0)) raiseIndexError();
			nimln_(157, "algorithm.nim");
			if ((NU)(i) >= (NU)(bLen_0)) raiseIndexError();
			unsureAsgnRef((void**) (&a[k]), b[i]);
			nimln_(158, "algorithm.nim");
			TM_JdC9c6SaUkvO1XjYuWP1JWQ_19 = addInt(k, ((NI) 1));
			k = (NI)(TM_JdC9c6SaUkvO1XjYuWP1JWQ_19);
			nimln_(159, "algorithm.nim");
			TM_JdC9c6SaUkvO1XjYuWP1JWQ_20 = addInt(i, ((NI) 1));
			i = (NI)(TM_JdC9c6SaUkvO1XjYuWP1JWQ_20);
		} LA25: ;
	}
	}BeforeRet_: ;
	popFrame();
}

N_NIMCALL(void, sort_9a7klSx0Yu33UIahhT1Of7Q)(NimStringDesc** a, NI aLen_0, TY_kTj9c3SX9agxDQPZYwemi6ug cmp, SortOrder_8iBc6wlNqBa9cju9cUAhUAxA order) {
	NI n;
	TY_sM4lkSb7zS6F7OVMvW9cffQ* b;
	NI TM_JdC9c6SaUkvO1XjYuWP1JWQ_7;
	NI s;
	nimfr_("sort", "algorithm.nim")
	nimln_(192, "algorithm.nim");
	n = aLen_0;
	b = (TY_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	nimln_(194, "algorithm.nim");
	TM_JdC9c6SaUkvO1XjYuWP1JWQ_7 = divInt(n, ((NI) 2));
	b = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), ((NI)chckRange((NI)(TM_JdC9c6SaUkvO1XjYuWP1JWQ_7), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(195, "algorithm.nim");
	s = ((NI) 1);
	{
		nimln_(196, "algorithm.nim");
		while (1) {
			NI m;
			NI TM_JdC9c6SaUkvO1XjYuWP1JWQ_8;
			NI TM_JdC9c6SaUkvO1XjYuWP1JWQ_9;
			NI TM_JdC9c6SaUkvO1XjYuWP1JWQ_26;
			if (!(s < n)) goto LA2;
			nimln_(197, "algorithm.nim");
			TM_JdC9c6SaUkvO1XjYuWP1JWQ_8 = subInt(n, ((NI) 1));
			TM_JdC9c6SaUkvO1XjYuWP1JWQ_9 = subInt((NI)(TM_JdC9c6SaUkvO1XjYuWP1JWQ_8), s);
			m = (NI)(TM_JdC9c6SaUkvO1XjYuWP1JWQ_9);
			{
				nimln_(198, "algorithm.nim");
				while (1) {
					NI TM_JdC9c6SaUkvO1XjYuWP1JWQ_21;
					NI TM_JdC9c6SaUkvO1XjYuWP1JWQ_22;
					NI TM_JdC9c6SaUkvO1XjYuWP1JWQ_23;
					NI TM_JdC9c6SaUkvO1XjYuWP1JWQ_24;
					NI TM_JdC9c6SaUkvO1XjYuWP1JWQ_25;
					if (!(((NI) 0) <= m)) goto LA4;
					nimln_(199, "algorithm.nim");
					TM_JdC9c6SaUkvO1XjYuWP1JWQ_21 = subInt(m, s);
					TM_JdC9c6SaUkvO1XjYuWP1JWQ_22 = addInt((NI)(TM_JdC9c6SaUkvO1XjYuWP1JWQ_21), ((NI) 1));
					TM_JdC9c6SaUkvO1XjYuWP1JWQ_23 = addInt(m, s);
					merge_KHePwML9ba2tSMRLHxcf3EQ(a, aLen_0, b->data, b->Sup.len, (((NI)(TM_JdC9c6SaUkvO1XjYuWP1JWQ_22) >= ((NI) 0)) ? (NI)(TM_JdC9c6SaUkvO1XjYuWP1JWQ_22) : ((NI) 0)), m, (NI)(TM_JdC9c6SaUkvO1XjYuWP1JWQ_23), cmp, order);
					nimln_(200, "algorithm.nim");
					TM_JdC9c6SaUkvO1XjYuWP1JWQ_24 = mulInt(s, ((NI) 2));
					TM_JdC9c6SaUkvO1XjYuWP1JWQ_25 = subInt(m, (NI)(TM_JdC9c6SaUkvO1XjYuWP1JWQ_24));
					m = (NI)(TM_JdC9c6SaUkvO1XjYuWP1JWQ_25);
				} LA4: ;
			}
			nimln_(201, "algorithm.nim");
			TM_JdC9c6SaUkvO1XjYuWP1JWQ_26 = mulInt(s, ((NI) 2));
			s = (NI)(TM_JdC9c6SaUkvO1XjYuWP1JWQ_26);
		} LA2: ;
	}
	popFrame();
}

N_NIMCALL(TY_sM4lkSb7zS6F7OVMvW9cffQ*, sorted_m77sjnalzCFloHeNRrZi6w)(NimStringDesc** a, NI aLen_0, TY_kTj9c3SX9agxDQPZYwemi6ug cmp, SortOrder_8iBc6wlNqBa9cju9cUAhUAxA order) {
	TY_sM4lkSb7zS6F7OVMvW9cffQ* result;
	nimfr_("sorted", "algorithm.nim")
	result = (TY_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	nimln_(206, "algorithm.nim");
	result = newSeq_9cL6dIz2UWtIh3FeS5x4hxA(((NI)chckRange(aLen_0, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(207, "algorithm.nim");
		colontmp_ = (aLen_0-1);
		nimln_(1955, "system.nim");
		res = ((NI) 0);
		{
			nimln_(1956, "system.nim");
			while (1) {
				NimStringDesc* T4_;
				NI TM_JdC9c6SaUkvO1XjYuWP1JWQ_6;
				if (!(res <= colontmp_)) goto LA3;
				nimln_(1957, "system.nim");
				i = res;
				if ((NU)(i) >= (NU)(result->Sup.len)) raiseIndexError();
				nimln_(208, "algorithm.nim");
				if ((NU)(i) >= (NU)(aLen_0)) raiseIndexError();
				T4_ = (NimStringDesc*)0;
				T4_ = result->data[i]; result->data[i] = copyStringRC1(a[i]);
				if (T4_) nimGCunrefNoCycle(T4_);
				nimln_(1976, "system.nim");
				TM_JdC9c6SaUkvO1XjYuWP1JWQ_6 = addInt(res, ((NI) 1));
				res = (NI)(TM_JdC9c6SaUkvO1XjYuWP1JWQ_6);
			} LA3: ;
		}
	}
	nimln_(209, "algorithm.nim");
	sort_9a7klSx0Yu33UIahhT1Of7Q(result->data, result->Sup.len, cmp, order);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void) {
	nimfr_("algorithm", "algorithm.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void) {
}

